name: ecom_analytics_demo 
profile: ecom_project
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

models:
  ecom_analytics_demo:
    +materialized: table

model-paths:
  - "staging"
  - "dimension_tables"
  - "facts_table"

